// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPPfq9YXqzQKAqYqUjksqX_ILSwCdD-9M',
    appId: '1:78016733517:android:b7d9baa42c05a4e8985704',
    messagingSenderId: '78016733517',
    projectId: 'asterhf-a5c24',
    databaseURL: 'https://asterhf-a5c24-default-rtdb.firebaseio.com',
    storageBucket: 'asterhf-a5c24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKfjAvI51z5O4WC6k_NhUklluJLgFV5KA',
    appId: '1:78016733517:ios:015dab329553dfe7985704',
    messagingSenderId: '78016733517',
    projectId: 'asterhf-a5c24',
    databaseURL: 'https://asterhf-a5c24-default-rtdb.firebaseio.com',
    storageBucket: 'asterhf-a5c24.appspot.com',
    iosClientId: '78016733517-1vnnnl415ejqj7ge62fpf8a7roj5b38m.apps.googleusercontent.com',
    iosBundleId: 'com.example.asterHf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKfjAvI51z5O4WC6k_NhUklluJLgFV5KA',
    appId: '1:78016733517:ios:015dab329553dfe7985704',
    messagingSenderId: '78016733517',
    projectId: 'asterhf-a5c24',
    databaseURL: 'https://asterhf-a5c24-default-rtdb.firebaseio.com',
    storageBucket: 'asterhf-a5c24.appspot.com',
    iosClientId: '78016733517-1vnnnl415ejqj7ge62fpf8a7roj5b38m.apps.googleusercontent.com',
    iosBundleId: 'com.example.asterHf',
  );
}
